### PR TITLE
Fix empty configuration path that leads to the extension not working

### LINKED ISSUE #105: When using a custom Dafny.dll and language server reset is hard
If I experiment with a custom version of Dafny,
reseting the IDE back takes reseting the config values to default
AND uninstall/reinstall.

I would be nice if I could just reset it in the config

### PR DESCRIPTION
**Pull request by MikaelMayer**
If someone deletes a configured language server runtime or compiler path, there will remain an empty string.

Previously, it would have been interpreted wrongly like a "relative path", and users would have needed to click on the gears icon next to the setting, and click "reset", which is unintuitive, since it was empty when they first edited it.

With this commit, it is correctly interpreted as "switch back to default"

This would have saved me the first time, and I just learned it would have saved someone else from spending a few hours of trouble.

Fixes #105

### CODE REVIEW

File: src/language/dafnyInstallation.ts [hunk 1]
```diff
@@ -15,17 +15,24 @@ import Configuration from '../configuration';
 const ArchiveFileName = 'dafny.zip';
 const mkdirAsync = promisify(fs.mkdir);
 
+// If someone deletes a configured language server runtime or compiler path, there will remain an empty string.
+// Previously, it would have been interpreted wrongly like a "relative path".
+// Now it is interpreted as "switch back to default"
+function ifNullOrEmpty(a: string | null, b: string) {
+  return a === "" || a == null ? b : a;
```
Comment (fabiomadge) [inline src/language/dafnyInstallation.ts:22]:
```suggestion
  return a === '' || a == null ? b : a;
```

**Comment by seebees** [comment]
I suspect that this will also fix #105.

File: src/language/dafnyInstallation.ts [hunk 2]
```diff
@@ -15,17 +15,24 @@ import Configuration from '../configuration';
 const ArchiveFileName = 'dafny.zip';
 const mkdirAsync = promisify(fs.mkdir);
 
+// If someone deletes a configured language server runtime or compiler path, there will remain an empty string.
+// Previously, it would have been interpreted wrongly like a "relative path".
+// Now it is interpreted as "switch back to default"
+function ifNullOrEmpty(a: string | null, b: string) {
```
Comment (keyboardDrummer) [inline src/language/dafnyInstallation.ts:21]: This seems like a strange function because `null` and `''` are both falsy in JavaScript, so instead of `isNullOrEmpty(a,b)`, I think you could also do `a || b`

Comment (MikaelMayer) [reply src/language/dafnyInstallation.ts:21]: Good point. I'll even inline a || b since it's so simple.

**Review by keyboardDrummer — APPROVED** [review]
There's a new warning now: "Unexpected nullable string value in conditional. Please handle the nullish/empty cases explicitly". 

I guess eslint disagrees with my suggestion. Feel free to use the previous version you had since that it was it's asking you to do, or otherwise turn off the warning with `// eslint-disable-next-line`

**Comment by MikaelMayer** [comment]
> // eslint-disable-next-line

I reverted to the previous one, but based on your suggestion, I simplified the conditional with `a ? a : b` instead of `a == ='' || a == null ? b : a`

**Review by camrein — APPROVED** [review]
> > // eslint-disable-next-line
> 
> I reverted to the previous one, but based on your suggestion, I simplified the conditional with `a ? a : b` instead of `a ==='' || a == null ? b : a`

I'm fine with both solutions. I tend to configure linters/static analyzers extremely strict and relax rules where needed. I suggest leaving the rule as is because the situation we've got here is rather seldom in my opinion. But an exception for this line is absolutely justified.

**Review by keyboardDrummer — APPROVED** [review]
