### PR TITLE
Fix disappearing resolution errors with verification tests.

### LINKED ISSUE #259: New test extension does not display parser and resolution errors anymore in the gutter
If deactivate the option "verification as tests"
image

If activate the option "verification as tests"
image

The icon is no longer displayed and the gutter is no longer grayed out.
The problem comes from the extension as the server correctly sends out the correct gutter icons in both case.

### PR DESCRIPTION
**Pull request by MikaelMayer**
Fixes #259 by short-circuiting the line skipping if there are resolution errors.

### CODE REVIEW

File: src/ui/verificationGutterStatusView.ts [hunk 1]
```diff
@@ -261,7 +261,9 @@ export default class VerificationGutterStatusView {
   private async getRangesOfLineStatus(params: IVerificationGutterStatusParams): Promise<Map<LineVerificationStatus, Range[]>> {
     const perLineStatus = this.addCosmetics(params.perLineStatus);
 
-    const symbolParams = (await this.symbolStatusView?.getVerifiableRanges(params.uri)) ?? [];
+    const symbolParams
+      = params.perLineStatus.indexOf(LineVerificationStatus.ResolutionError) > 0 ? []
+        : (await this.symbolStatusView?.getVerifiableRanges(params.uri)) ?? [];
```
Comment (keyboardDrummer) [inline src/ui/verificationGutterStatusView.ts:266]: Could you also change this to `await (this.symbolStatusView?.getVerifiableRanges(params.uri) ?? Promise.resolve([]))` ?

**Review by keyboardDrummer — APPROVED** [review]
