### PR TITLE
fix: relax .NET runtime version check

### LINKED ISSUE #442: (offer to help) installation via VSCode on mac M1
I was wondering if I could help with anything to make the installation via VSCode work more smoothly on mac. Are there known tracking issues currently with this process that I may have missed?

My installation seems to be set up now, but I wasn't able to get it working initially, and I'll share some details below. I'm sure I did some things wrong, but it wasn't obvious at first.

The extension initially installed but silently produced no output (not catching assertion violations). Later it prompted that the installation of dotnet was not found. I got the following error:
```
/usr/local/share/dotnet/dotnet is not a compatible dotnet file. Dafny requires the ASP.NET Core Runtime 5.0 or 6.0, got Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App] Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App] Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

The error did not go away when installing .NET via the official website, using the provided link, even after uninstalling/reinstalling extensions and restarting VSCode.

What seemed to work was running `brew install dotnet-sdk`, uninstalling and reinstalling all the relevant vscode extensions, and restarting VSCode. Now I am correctly finding assertion violations.

My setup: I'm running on a MacBook Air (M1 chip, 2020) with VSCode version: 1.82.3 (Universal). Additional details:
```
Commit: fdb98833154679dbaa7af67a5a29fe19e55c2b73
Date: 2023-10-02T11:06:17.496Z (1 wk ago)
Electron: 25.8.1
ElectronBuildId: 24153832
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 21.4.0
```

Thanks!

### PR DESCRIPTION
**Pull request by alex-chew**
Fixes #442.

* Relaxes the .NET runtime version check to only require the .NET Runtime (instead of ASP.NET Core too), and to permit versions later than 6.0.x.
* Make the version check error message more concise, in order to reduce the likelihood that VS Code hides the notification (due to the message being too long to fit on screen).

### CODE REVIEW

File: src/ui/messages.ts [hunk 1]
```diff
@@ -29,9 +29,9 @@ export namespace Messages {
 
   export namespace Dotnet {
     export const IsNotAnExecutableFile = ' is not an executable dotnet file.';
-    export const NotASupportedDotnetInstallation = ' is not a compatible dotnet file. Dafny requires the ASP.NET Core Runtime 5.0 or 6.0, got ';
-    export const FailedDotnetExecution = 'Failed to execute dotnet. Dafny requires the ASP.NET Core Runtime 5.0 or 6.0.';
-    export const NoCompatibleInstallation = 'No compatible dotnet runtime found. Dafny requires the ASP.NET Core Runtime 5.0 or 6.0.';
+    export const NotASupportedDotnetInstallation = ' is not a compatible dotnet file. Dafny requires the .NET Runtime 5.0 or greater, found ';
+    export const FailedDotnetExecution = 'Failed to execute dotnet. Dafny requires the .NET Runtime 5.0 or greater.';
+    export const NoCompatibleInstallation = 'No compatible dotnet runtime found. Dafny requires the .NET Runtime 5.0 or greater.';
```
Comment (robin-aws) [inline src/ui/messages.ts:34]: Side note, I'm a bit surprised we need three different error messages, implying there are three different places we check this?

**Review by robin-aws — APPROVED** [review]

File: src/ui/messages.ts (hunk 1 above)
Comment (alex-chew) [reply src/ui/messages.ts:34]: Hmm, it's possible that the "Dafny requires the .NET Runtime 5.0 or greater" part is redundant, but indeed the three messages are used in three distinct failure modes (successfully executed `dotnet --list-runtimes` but found no compatible version; failed to execute `dotnet` with a manually-specified executable; and failed to execute `dotnet` using `$PATH`).
